version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      ANDROID_HOME: /usr/local/android-sdk-linux
    dependencies:
      pre:
        - echo y | android update sdk --no-ui --all --filter "android-26"
        - echo y | android update sdk --no-ui --all --filter "build-tools-26.0.1"
        - echo y | android update sdk --no-ui --all --filter "extra-android-m2repository"
        - echo y | android update sdk --no-ui --all --filter "extra-google-m2repository"
      override:
        - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies
      post:
        - cp local.properties.ci local.properties

    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
          
          
